% Setting trajectory generation parameters
%% Create agent folder for saved agents
rng(0);
agent_folder = 'Agents_trained';
if ~exist(agent_folder, 'dir')
    mkdir(agent_folder)
end
sampleTime = 0.1;
time_allocated=30; %in s


% Randomly generated trajectory saved and loaded
ref=load('random_path.mat').list_paths_to_track;

connection = simulation_openConnection(simulation_setup(), 0);
omni_init(connection);
bodyDiameter=1.000;
wheelDiameter=0.100;
coupling_matrix=(2/wheelDiameter)*[-0.7071  0.7071 -bodyDiameter/2; ...
                0.7071  0.7071 -bodyDiameter/2; ...
                0.7071  -0.7071 -bodyDiameter/2; ...
                -0.7071  -0.7071 -bodyDiameter/2];
% Creating Environment
env = omniEnv_SAC(connection,sampleTime,coupling_matrix,ref);
validateEnvironment(env)
obsInfo = getObservationInfo(env);
actInfo = getActionInfo(env);

% Creating RL Entities
[critic1,critic2] = build_critic_SAC(obsInfo, actInfo);
actor = build_actor_SAC(obsInfo, actInfo);
criticOptions = rlOptimizerOptions( ...
    Optimizer="adam", ...
    LearnRate=1e-3,... 
    GradientThreshold=1, ...
    L2RegularizationFactor=2e-4);
actorOptions = rlOptimizerOptions( ...
    Optimizer="adam", ...
    LearnRate=1e-3,...
    GradientThreshold=1, ...
    L2RegularizationFactor=1e-5);
steps_per_episode = ceil((time_allocated)/sampleTime);
%% Agent options
agentOptions = rlSACAgentOptions(...
    'SampleTime',env.Ts,...
    'TargetSmoothFactor',1e-3,...
    'ExperienceBufferLength',5e5,...
    'TargetUpdateFrequency', 3,...
    'NumStepsToLookAhead',5,...
    'CriticOptimizerOptions',criticOptions,...
    'ActorOptimizerOptions', actorOptions,...
    'MiniBatchSize',128);
agent = rlSACAgent(actor,[critic1,critic2],agentOptions);

target_agent_name = "SAC_static_dynamic_test";
SaveAgentDirectory = fullfile(agent_folder,'agent_SAC_static_complex.mat');
% Training Agent in Environment
opt = rlTrainingOptions(...
    'MaxEpisodes',2000,...
    'MaxStepsPerEpisode',steps_per_episode,...
    'StopTrainingCriteria',"AverageReward",...
    "ScoreAveragingWindowLength",10,...
    'SaveAgentDirectory', SaveAgentDirectory,...
    'StopTrainingValue',500);
load(opt.SaveAgentDirectory,'agent');
%agent.AgentOptions.EntropyWeightOptions.TargetEntropy = -10;
agent.AgentOptions.ActorOptimizerOptions.LearnRate=4e-4;
agent.AgentOptions.CriticOptimizerOptions(1,1).LearnRate=8e-4;
agent.AgentOptions.CriticOptimizerOptions(1,2).LearnRate=8e-4;
% agent.ActionInfo.LowerLimit = -30;
% agent.ActionInfo.UpperLimit = 30;
trainStats = train(agent,env,opt);
save(fullfile(agent_folder,strcat('trainStats_',target_agent_name)),'trainStats');
save(fullfile(agent_folder,strcat('agent_', target_agent_name)),'agent');